### ISSUE TITLE
增加人数趋势

### ISSUE THREAD

**Issue by xrkffgg** [zoo-js/zoo-charts#1]
现有项目使用了 roughViz 一个比较冷门，但是可爱的一个 图表插件。
拟加入 总人数的成长趋势图。

满足以下功能：
1. 默认显示当月日成长趋势。数量为20，若不足20，取上个月数据。
2. 可使用 tab 切换显示月份成长趋势。
3. 显示年份成长趋势。

现有几点想听听大家想法：

### 数据存储

假如存储 total和 time，

1. 是直接存，

```json
[
  {
    "total": 100,
    "time": "2020-10-01",
  },
  {
    "total": 101,
    "time": "2020-10-02",
  }
]
```

> 这样前端请求到数据后，要进行数组组装。获取最新的20条，并且月份，年份要累加。

2. 根据时间生成层级

直接生成年数据、月数据、日数据。每天脚本统计时，自动更新。

> 好像这样一分析，第二种好一点。

### 图表展示

是仍然使用 https://github.com/jwilber/roughViz

还是更改为主流的 echarts g2 等产品

**Comment by xrkffgg** [comment]
人数的数据格式确认后，我来补全之前的一些数据。

**Comment by zcong1993** [comment]
第二种包含了第一种是吧

**Comment by xrkffgg** [comment]
第二种的话，我的想法是

year类型里面，total date，这个没异议

month类型里，就有多种了。因为有20年1月，也有21年1月。是先分个年，再月和数据，还是直接月和数据。

因为涉及到显示的时候，月统计，应该是显示当年各个月份的人数，这样先分年的这种数据更直接。

然后是日统计的时候，默认显示当月的，但是可以选择看的，可以选2月，3月，去年2月，去年3月。这样日统计数据要分3层了。

还有一个，是把这些放一个json，还是分不同的json放。

**Comment by xrkffgg** [comment]
😂😂好像github没有在线数据库的。其实用json存放，请求也可以。

**Comment by xrkffgg** [comment]
其实分层也还好。第一次麻烦点。写好脚本后，定时actions跑。

目前是每天会统计下人数。

再增加几个actions每个月统计一下月的

年的话，暂时可以不考虑

**Comment by zcong1993** [comment]
白嫖这个吧 https://dashboard.fauna.com 挺好用的 cloud nosql, 自带 graphql API

**Comment by xrkffgg** [comment]
这个是数据存到这个平台的？

**Comment by zcong1993** [comment]
对, 我个人的一些私人配置就是这么搞的

**Comment by xrkffgg** [comment]
😂😂定时自动更新数据，好支持吗？

**Comment by zcong1993** [comment]
graphql API, 太容易了

**Comment by xrkffgg** [comment]
明天看看😂😂

**Comment by xrkffgg** [comment]
也许是我想的太复杂了，或许不用那么麻烦😂，只显示个总人数好了。
